name = input("An wen geht diese Nachricht? ")
absender = input("Wer ist der Absender? ")

print(f"Hey {name}")
print("")
print("Mit dieser E-Mail möchte ich dich über meine neue Adresse informieren.")
print("")
print("Musterstraße 123")
print("1234 Musterhausen")
print("")
print("Viele Grüße")
print(f"{absender}")